# -*- coding: utf-8 -*-
"""LinearRegression_with_multiplevariables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Kshitijzaeden/ml2/blob/main/LinearRegression_with_multiplevariables.ipynb
"""

import numpy as np
import pandas as pd
from sklearn import linear_model

import warnings
warnings.filterwarnings('ignore')

"""DATASET FOR MAKING/TRAINING THE MODEL"""

df=pd.read_csv("houseprice.csv")
print(df.head())

df.isnull()

"""*MODEL TRAINING * with multivariate variables"""

model=linear_model.LinearRegression()
model.fit(df.drop('price',axis="columns"),df.price)

model.predict([[5,5,2000,10500]])

model.coef_

model.intercept_

"""Below is the answer of how the model predicted the answer by adding all coef and intercept"""

(-5.50670442e+04)*5+(-9.22258847e+03)*5+(2.94373093e+02)*2000+(-7.65989982e-01)*10500+140172.13958227268